### ISSUE TITLE
[OTHER] - Module Dependency Query

### ISSUE THREAD

**Issue by dmc1899** [Hemanthhari2000/todo-app-ports-and-adapters#1]
### What would you like to share?

Hi there,

I was reading your recent blog https://hemanthhari2000.medium.com/the-ports-and-adapters-pattern-unraveling-the-mystery-2efbf678ab9b and took a look at your code and have a question.

In your service.py inside your `domain` you have this line https://github.com/Hemanthhari2000/todo-app-ports-and-adapters/blob/3d8b8e1a1549c291b1f9c73b53499ada7bd5c272/src/domain/todo/service.py#L11 which explicitly creates a dependency on your `TodoAdapter`.

Does dependency not break the entire premise of having the domain not depend on the outside world (i.e. the adapters)?

### Would you like to work on this issue?

- [ ] Yes, I want to work on this issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dmc1899** [comment]
I also think that the image you have published here is incorrect - https://miro.medium.com/v2/resize:fit:720/format:webp/1*qQNw52pWUE-l4Kf9MnIbIQ.png

This image implies that an Adapter implements a Port on the Driving side of the Hexagon.

Adapters _use_ ports on the Driving side and _implement_ ports on the Driven side.

**Comment by Hemanthhari2000** [comment]
Hey,
Oops, that’s totally on me! I’ll fix the code and image in a bit. Thanks a lot for catching that—really appreciate it!

**Comment by Hemanthhari2000** [comment]
Updated the image as well.
